// stting variables for action types to prevent errors generated by typeo while writting the action type name at lot of places. this variables still reffer to string
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

//type for REST API
export const CREATE_STREAM = "CREATE_STREAM";
export const FETCH_STREAMS = "FETCH_STREAMS";
export const FETCH_STREAM = "FETCH_STREAM";
export const DELETE_STREAM = "DELETE_STREAM";
export const EDIT_STREAM = "EDIT_STREAM";
