// stting variables for action types to prevent errors generated by typeo while writting the action type name at lot of places. this variables still reffer to string
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
